stages:
  - build

build:
  stage: build
  script:
    - npm install
    - npm run build
    - sudo cp -r ./dist/* /var/www/frontend.nuaris.co/
  artifacts:
    paths:
      - dist
  only:
    - development
